name: Hello World
run-name: ${{ github.actor }} Hello world
on: [push]
jobs:
  Hello-World-Action:
    runs-on: ubuntu-latest
    steps:
      # - uses: actions/checkout@v5
      # - uses: actions/setup-node@v4
      #   with:
      #     node-version: "20"
      - run: echo "Hello World"
